Repository bcgov/pubcode, pull requests merged in 2023-06, with the labels that each got.

#202 Changes to integrate with CHES for email notification in failures.
  .github/workflows/merge-main.yml
  .github/workflows/pr-open.yml
  .github/workflows/prod.yml
  api/Dockerfile
  api/openshift.deploy.yml
  api/package-lock.json
  api/package.json
  api/src/email/ches-service.js
  api/src/email/connection.js
  api/src/email/index.js
  api/src/services/pub-code-service.js
  common/openshift.init.yml
Labels: enhancement

#206 workflow fixes.
  .github/workflows/merge-main.yml
  .github/workflows/prod.yml
Labels: bug

#209 Disable Dependabot dep updates, using Renovate
  .github/dependabot.yml
Labels: dependencies

#210 207 use template for generating html content in api
  .github/workflows/merge-main.yml
  .github/workflows/pr-open.yml
  .gitignore
  api/src/email/ches-service.js
  api/src/services/pub-code-service.js
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/cypress.config.js
  frontend/cypress/e2e/edit-form.cy.js
  frontend/cypress/e2e/home-page.cy.js
  frontend/cypress/e2e/left-drawer.cy.js
  frontend/cypress/e2e/new-form.cy.js
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/e2e.js
  frontend/cypress/support/index.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/EditForm.jsx
  frontend/src/components/FormComponent.jsx
  frontend/src/components/LeftDrawer.jsx
  frontend/src/main.jsx
  sysdig/sysdig.yml
Labels: enhancement

#215 update caddy to 2.6.4 alpine
  .github/workflows/pr-open.yml
  frontend/Caddyfile
  frontend/Dockerfile
  frontend/openshift.deploy.yml
Labels: enhancement
