Repository bcgov/pubcode, pull requests merged in 2023-02, with the labels that each got.

#76 Bump Mongo PVC to 512Mi
  database/openshift.deploy.yml
Labels: bug

#79 feat: initial commit to get the api up and running in openshift.
  .github/workflows/merge-main.yml
  .github/workflows/pr-open.yml
  backend/Dockerfile
  backend/openshift.deploy.yml
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/db/database.js
  backend/src/entities/pub-code-entity.js
  backend/src/logger.js
  backend/src/routes/pubcode-router.js
  backend/src/server.js
  backend/src/services/pub-code-service.js
  common/openshift.init.yml
  database/openshift.deploy.yml
  docker-compose.yml
Labels: MVP

#81 Docker adjustments, health checks
  backend/Dockerfile
  database/Dockerfile
  frontend/Dockerfile
Labels: enhancement

#85 various updates
  backend/README.md
  docker-compose.yml
  frontend/Caddyfile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/LeftDrawer.jsx
  frontend/src/components/NotFound.jsx
  frontend/src/routes/index.jsx
Labels: bug, enhancement, MVP

#86 pr-close + promotions for database and backend
  .github/workflows/merge-main.yml
  .github/workflows/pr-close.yml
Labels: enhancement

#87 PROD deployment
  backend/openshift.deploy.yml
  database/openshift.deploy.yml
  frontend/openshift.deploy.yml
Labels: enhancement

#89 speed up query and dont wait for bulk-load
  backend/src/services/pub-code-service.js
Labels: bug, MVP

#93 code changes for adding rate limiting.
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/routes/pubcode-router.js
Labels: enhancement, MVP

#96 commenting out search and updating rjsf to 5
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Dashboard.jsx
  frontend/src/components/LeftDrawer.jsx
Labels: dependencies, MVP

#98 Query speed up and return limited fields.
  .github/workflows/pubcode-crawler-on-scheduler.yml
  backend/package-lock.json
  backend/package.json
  backend/src/schedulers/refresh-cache.js
  backend/src/server.js
  backend/src/services/cache-service.js
  backend/src/services/pub-code-service.js
Labels: bug, dependencies, javascript, MVP

#100 Test crawler cronjob/dispatch rights
  .github/workflows/pubcode-crawler-on-scheduler.yml
  crawler/src/main.js
Labels: enhancement

#101 Provide API key to crawler
  .github/workflows/pubcode-crawler-on-scheduler.yml
  crawler/src/main.js
Labels: enhancement

#103 documentation updates.
  README.md
  backend/README.md
  frontend/README.md
  schema/README.md
Labels: documentation, MVP

#104 Added Arch Diagram.
  docs/pub-code.drawio
  docs/pub-code.png
Labels: documentation, MVP

#109 Added API call from crawler.
  .github/workflows/pubcode-crawler-on-scheduler.yml
  backend/src/entities/pub-code-entity.js
  backend/src/services/pub-code-service.js
  crawler/src/main.js
  frontend/README.md
Labels: enhancement, javascript, github_actions, MVP
