Repository bcgov/pubcode, pull requests merged in 2023-03, with the labels that each got.

#138 Break out prod portion of deployment into own workflow
  .github/workflows/merge-main.yml
  .github/workflows/prod.yml
Labels: enhancement

#142 refresh cache and reduce log noise
  backend/src/app.js
  backend/src/schedulers/refresh-cache.js
  backend/src/server.js
Labels: enhancement, javascript

#144 replace cache entries instead of infinitely adding items to it.
  backend/src/services/cache-service.js
Labels: bug, javascript

#139 Basic schema issue type
  .github/ISSUE_TEMPLATE/schema.md
Labels: enhancement, schema

#147 Update repo links
  .github/workflows/merge-main.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  .github/workflows/prod.yml
  .github/workflows/pubcode-crawler-on-scheduler.yml
  .github/workflows/tests.yml
  README.md
  SECURITY.md
  api/Dockerfile
  api/README.md
  api/openshift.deploy.yml
  api/package-lock.json
  api/package.json
  api/src/app.js
  api/src/db/database.js
  api/src/entities/pub-code-entity.js
  api/src/logger.js
  api/src/routes/pubcode-router.js
  api/src/schedulers/refresh-cache.js
  api/src/server.js
  api/src/services/cache-service.js
  api/src/services/pub-code-service.js
  bcgovpubcode.yml
  common/openshift.init.yml
  crawler/package-lock.json
  crawler/package.json
  database/openshift.deploy.yml
  docker-compose.yml
  frontend/README.md
  frontend/openshift.deploy.yml
  frontend/src/components/FormComponent.jsx
Labels: enhancement

#151 Rebuild images
  .github/workflows/pr-open.yml
  common/openshift.init.yml
Labels: bug

#156 Get crawler URL from route
  .github/workflows/pubcode-crawler-on-scheduler.yml
Labels: enhancement

#158 Add https:// to crawler url
  .github/workflows/pubcode-crawler-on-scheduler.yml
Labels: bug

#160 Add few extra fields to crawler for nice visualization
  api/src/entities/pub-code-entity.js
  crawler/src/main.js
  frontend/Caddyfile
Labels: enhancement
